// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tormyesdqesbygzlymrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvcm15ZXNkcWVzYnlnemx5bXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzkxMjEsImV4cCI6MjA3NDMxNTEyMX0.QkkUOcmimBiJbDIgCZ5tp9XqQS1DvaF_0tFNuZXrqbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});